### PR TITLE
Demo example for table API

### PR DESCRIPTION
**Pull request by JetSetIlly**
I've updated the Go demo window to include a couple of examples using the new Table API.

This was a way for me to try out the API in the simplest way possible. It may be useful/instructive for others too.
 
Screenshot from 2021-02-18 09-49-41

tagging @the-goodies because they added the table API to imgui-go

### CODE REVIEW

**Comment by dertseha** [comment]
Great, thank you for the contribution. Let's wait until the library is available in v4, and the complexity linter most likely needs to be disabled for the demo file.

**Comment by dertseha** [comment]
May I ask you to come back to this and update the dependency to the newest released version of `imgui-go`? Extending the demo window is highly appreciated.

As for the linters, disable them in `.golangci.yml` because I guess they will be all over these demo window entries.

**Comment by JetSetIlly** [comment]
Done.

**Comment by dertseha** [comment]
Thank you for your contribution!

**Pull request merged**
